In [2]:
import pandas as pd
import numpy as np

In [5]:
aus_tourism = pd.read_csv("C:\\Users\\dell\\forecasting\\aus_tourism.csv", parse_dates=["ds"])
aus_tourism.head(10)

                           unique_id         ds           y
0  Adelaide-South Australia-Business 1998-03-31  135.077690
1  Adelaide-South Australia-Business 1998-06-30  109.987316
2  Adelaide-South Australia-Business 1998-09-30  166.034687
3  Adelaide-South Australia-Business 1998-12-31  127.160464
4  Adelaide-South Australia-Business 1999-03-31  137.448533
5  Adelaide-South Australia-Business 1999-06-30  199.912586
6  Adelaide-South Australia-Business 1999-09-30  169.355090
7  Adelaide-South Australia-Business 1999-12-31  134.357937
8  Adelaide-South Australia-Business 2000-03-31  154.034398
9  Adelaide-South Australia-Business 2000-06-30  168.776364

In [6]:
mean_df = aus_tourism.groupby("unique_id", as_index=False)["y"].mean()
mean_df

                                    unique_id           y
0     Adelaide Hills-South Australia-Business    2.664236
1      Adelaide Hills-South Australia-Holiday   10.467276
2        Adelaide Hills-South Australia-Other    1.404931
3     Adelaide Hills-South Australia-Visiting   14.202530
4           Adelaide-South Australia-Business  155.527910
..                                        ...         ...
299                 Wimmera-Victoria-Visiting   14.879986
300  Yorke Peninsula-South Australia-Business    6.892481
301   Yorke Peninsula-South Australia-Holiday   80.088485
302     Yorke Peninsula-South Australia-Other    1.885884
303  Yorke Peninsula-South Australia-Visiting   28.146552

[304 rows x 2 columns]

In [7]:
mean_df.sort_values(by="y").head(10)

                                  unique_id         y
158   Kangaroo Island-South Australia-Other  0.340347
182     MacDonnell-Northern Territory-Other  0.449004
294          Wilderness West-Tasmania-Other  0.478268
34          Barkly-Northern Territory-Other  0.632386
86       Clare Valley-South Australia-Other  0.897749
38            Barossa-South Australia-Other  1.021521
154  Kakadu Arnhem-Northern Territory-Other  1.042653
170       Lasseter-Northern Territory-Other  1.135796
298                  Wimmera-Victoria-Other  1.146237
183  MacDonnell-Northern Territory-Visiting  1.175393